/* Generated by re2c 1.3 on Tue Aug 25 17:18:03 2020 */
#line 1 "jwl/jwl_http.l"
/* Copyright (c) [2019] juruoyun developer team
   Juruoyun web lib is licensed under the Mulan PSL v1.
   You can use this software according to the terms and conditions of the Mulan PSL v1.
   You may obtain a copy of Mulan PSL v1 at:
      http://license.coscl.org.cn/MulanPSL
   THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
   PURPOSE.
   See the Mulan PSL v1 for more details.*/
#include "jwl_http.h"
#if JWL_HTTP_ENABLE==1
jwl_http_head *jwl_http_head_new()
{
	return jwl_http_head_init(jbl_malloc(sizeof(jwl_http_head)));
}
jwl_http_head *jwl_http_head_init(jwl_http_head * this)
{
	if(!this)jbl_exception("NULL POINTER");		
	jbl_gc_init(this);
	jbl_gc_plus(this);
	this->status		=0;
	this->charset		=0;	
	this->content_type	=0;
	
	this->method		=0;
	this->protocol		=0;
	
	this->connection	=0;
	this->cache			=0;
	this->upgrade		=0;
	this->cache_max_age	=0;	
	this->range.start	=0;	
	this->range.end		=0;	
	this->etag			=NULL;

//jbl_string
	this->filename		=NULL;

	this->url			=NULL;
	this->host			=NULL;
	this->ua			=NULL;
	this->referer		=NULL;
//jbl_ht
	this->cookie		=NULL;
	this->v				=NULL;	
	this->parameter		=NULL;	

	this->cond			=0;	
	return this;
}
jwl_http_head *jwl_http_head_free(jwl_http_head * this)
{
	if(!this)return NULL;
	jbl_gc_minus(this);
	if(!jbl_gc_refcnt(this))
	{
		if(jbl_gc_is_ref(this))
			jwl_http_head_free((jwl_http_head*)(((jbl_reference*)this)->ptr));
		else
		{
			this->etag			=jbl_string_free(this->etag);
			
			this->filename		=jbl_string_free(this->filename);
			
			this->url			=jbl_string_free(this->url);
			this->host			=jbl_string_free(this->host);
			this->ua			=jbl_string_free(this->ua);
			this->referer		=jbl_string_free(this->referer);
			this->v				=jbl_ht_free	(this->v);
			this->cookie		=jbl_ht_free	(this->cookie);
			this->parameter		=jbl_ht_free	(this->parameter);
		}
		if(jbl_gc_is_var(this))//因为该功能依赖jbl_ht,jbl_ht强制依赖var所以不用宏判断
			jbl_free((char*)this-sizeof(jbl_var));
		else
			jbl_free(this);
	}
	return NULL;	
	
}
inline jwl_http_head *jwl_http_head_copy(jwl_http_head * this)
{
	jbl_gc_plus(this);
	return this;
}
inline jwl_http_head *jwl_http_head_extend(jwl_http_head * this,jwl_http_head **pthi)
{
	if(!this){this=jwl_http_head_new();if(pthi)*pthi=this;return this;}
	jbl_reference *ref=NULL;jwl_http_head *thi=jbl_refer_pull_keep_father(this,&ref);
	if(jbl_gc_is_pvar(thi))
	{
		jwl_http_head *ttt=((jbl_reference*)thi)->ptr;
		if(jbl_gc_refcnt(thi)==1)
			((jbl_reference*)thi)->ptr=NULL,
		jwl_http_head_free(thi);
		thi=ttt;
	}	
	if((jbl_gc_refcnt(thi)<=1)){if(pthi)*pthi=thi;return this;}

	jwl_http_head * tmp	=jwl_http_head_new();
	
	tmp->status			=this->status;
	tmp->charset		=this->charset;
	tmp->content_type	=this->content_type;
	
	tmp->method			=this->method;
	tmp->protocol		=this->protocol;
	tmp->connection		=this->connection;
	
	tmp->cache			=this->cache;
	tmp->upgrade		=this->upgrade;
	tmp->cache_max_age	=this->cache_max_age;
	tmp->range.start	=this->range.start;
	tmp->range.end		=this->range.end;
	tmp->etag			=jbl_string_copy(this->etag);
	
	
	tmp->filename		=jbl_string_copy(this->filename);
	
	
	tmp->url			=jbl_string_copy(this->url);
	tmp->host			=jbl_string_copy(this->host);
	tmp->ua				=jbl_string_copy(this->ua);
	tmp->referer		=jbl_string_copy(this->referer);
	
	tmp->cookie			=jbl_ht_copy(this->cookie);
	tmp->v				=jbl_ht_copy(this->v);
	tmp->parameter		=jbl_ht_copy(this->parameter);
	
	jwl_http_head_free(this);
	if(ref)		ref->ptr=tmp;
	else		this=tmp;
	if(pthi)	*pthi=tmp;	
	return this;
}
jwl_http_head *		jwl_http_head_set_status		(jwl_http_head * this,jbl_uint32			status)			{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->status		=status			;return this;}
jwl_http_head *		jwl_http_head_set_charset		(jwl_http_head * this,jwl_http_charset		charset)		{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->charset		=charset  		;return this;}
jwl_http_head *		jwl_http_head_set_content_type	(jwl_http_head * this,jbl_file_ct			content_type)	{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->content_type	=content_type	;return this;}
jwl_http_head *		jwl_http_head_set_method		(jwl_http_head * this,jwl_http_method		method)			{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->method		=method  		;return this;}
jwl_http_head *		jwl_http_head_set_protocol		(jwl_http_head * this,jwl_http_protocol		protocol)		{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->protocol		=protocol  		;return this;}
jwl_http_head *		jwl_http_head_set_connection	(jwl_http_head * this,jwl_http_connection	connection)		{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->connection	=connection		;return this;}
jwl_http_head *		jwl_http_head_set_cache			(jwl_http_head * this,jwl_http_cache		cache)			{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->cache			=cache  		;return this;}
jwl_http_head *		jwl_http_head_set_upgrade		(jwl_http_head * this,jwl_http_upgrade		upgrade)		{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->upgrade		=upgrade  		;return this;}
jwl_http_head *		jwl_http_head_set_cache_max_age	(jwl_http_head * this,jbl_uint32			cache_max_age)	{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->cache_max_age	=cache_max_age	;return this;}
jwl_http_head *		jwl_http_head_set_range			(jwl_http_head * this,jwl_http_head_range	range)			{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->range			=range			;return this;}
jwl_http_head *		jwl_http_head_set_etag			(jwl_http_head * this,jbl_string *	etag)					{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);jbl_string_free(thi->etag)			;thi->etag			=jbl_string_copy(etag)							;return this;}
jwl_http_head *		jwl_http_head_set_filename		(jwl_http_head * this,jbl_string * filename)				{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);jbl_string_free(thi->filename)		;thi->filename		=jbl_string_copy(filename)						;return this;}
jwl_http_head *		jwl_http_head_set_url			(jwl_http_head * this,jbl_string * url)						{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);jbl_string_free(thi->url)			;thi->url			=jbl_string_copy(url)							;return this;}
jwl_http_head *		jwl_http_head_set_host			(jwl_http_head * this,jbl_string * host)					{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);jbl_string_free(thi->host)			;thi->host			=jbl_string_copy(host)							;return this;}
jwl_http_head *		jwl_http_head_set_ua			(jwl_http_head * this,jbl_string * ua)						{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);jbl_string_free(thi->ua)			;thi->ua			=jbl_string_copy(ua)							;return this;}
jwl_http_head *		jwl_http_head_set_referer		(jwl_http_head * this,jbl_string * referer)					{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);jbl_string_free(thi->referer)		;thi->referer		=jbl_string_copy(referer)						;return this;}
jwl_http_head *		jwl_http_head_set				(jwl_http_head * this,unsigned char * key,jbl_var* var)		{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi)									;thi->v				=jbl_ht_insert_chars(thi->v			,key,var)	;return this;}
jwl_http_head *		jwl_http_head_set_parameter		(jwl_http_head * this,unsigned char * key,jbl_var* var)		{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);									thi->parameter		=jbl_ht_insert_chars(thi->parameter	,key,var)	;return this;}
jwl_http_head *		jwl_http_head_set_cookie		(jwl_http_head * this,unsigned char * key,jbl_var* var)		{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);									thi->cookie			=jbl_ht_insert_chars(thi->cookie	,key,var)	;return this;}

jbl_uint32			jwl_http_head_get_status		(jwl_http_head * this){if(!this)return 0;this=jbl_refer_pull(this);return this->status;}
jwl_http_charset	jwl_http_head_get_charget		(jwl_http_head * this){if(!this)return 0;this=jbl_refer_pull(this);return this->charset;}
jbl_file_ct			jwl_http_head_get_content_type	(jwl_http_head * this){if(!this)return 0;this=jbl_refer_pull(this);return this->content_type;}
jwl_http_method		jwl_http_head_get_method		(jwl_http_head * this){if(!this)return 0;this=jbl_refer_pull(this);return this->method;}
jwl_http_protocol	jwl_http_head_get_protocol		(jwl_http_head * this){if(!this)return 0;this=jbl_refer_pull(this);return this->protocol;}
jwl_http_connection	jwl_http_head_get_connection	(jwl_http_head * this){if(!this)return 0;this=jbl_refer_pull(this);return this->connection;}
jwl_http_cache		jwl_http_head_get_cache			(jwl_http_head * this){if(!this)return 0;this=jbl_refer_pull(this);return this->cache;}
jwl_http_upgrade	jwl_http_head_get_upgrade		(jwl_http_head * this){if(!this)return 0;this=jbl_refer_pull(this);return this->upgrade;}
jbl_uint32			jwl_http_head_get_cache_max_age	(jwl_http_head * this){if(!this)return 0;this=jbl_refer_pull(this);return this->cache_max_age;}
jwl_http_head_range	jwl_http_head_get_range			(jwl_http_head * this){if(!this)return (jwl_http_head_range){0,0};this=jbl_refer_pull(this);return this->range;}
jbl_string *		jwl_http_head_get_etag			(jwl_http_head * this){if(!this)return NULL;this=jbl_refer_pull(this);return jbl_string_copy(this->etag);}
jbl_string *		jwl_http_head_get_filename		(jwl_http_head * this){if(!this)return NULL;this=jbl_refer_pull(this);return jbl_string_copy(this->filename);}
jbl_string *		jwl_http_head_get_url			(jwl_http_head * this){if(!this)return NULL;this=jbl_refer_pull(this);return jbl_string_copy(this->url);}
jbl_string *		jwl_http_head_get_host			(jwl_http_head * this){if(!this)return NULL;this=jbl_refer_pull(this);return jbl_string_copy(this->host);}
jbl_string *		jwl_http_head_get_ua			(jwl_http_head * this){if(!this)return NULL;this=jbl_refer_pull(this);return jbl_string_copy(this->ua);}
jbl_string *		jwl_http_head_get_referer		(jwl_http_head * this){if(!this)return NULL;this=jbl_refer_pull(this);return jbl_string_copy(this->referer);}
jbl_var    *		jwl_http_head_get				(jwl_http_head * this,unsigned char * key){if(!this)return NULL;this=jbl_refer_pull(this);if(!this->v)			return NULL;return jbl_ht_get_chars(this->v,key);}
jbl_var    *		jwl_http_head_get_parameter		(jwl_http_head * this,unsigned char * key){if(!this)return NULL;this=jbl_refer_pull(this);if(!this->parameter)	return NULL;return jbl_ht_get_chars(this->parameter,key);}
jbl_var    *		jwl_http_head_get_cookie		(jwl_http_head * this,unsigned char * key){if(!this)return NULL;this=jbl_refer_pull(this);if(!this->cookie)		return NULL;return jbl_ht_get_chars(this->cookie,key);}





void jwl_http_head_encode(jwl_http_head *head,jbl_stream *stream,jbl_string_size_type size)
{
#define rn() jbl_stream_push_char(stream,'\r'),jbl_stream_push_char(stream,'\n')
	if(!head)return;
	head=jbl_refer_pull(head);
	if(jwl_http_head_is_response(head))
	{
		jbl_stream_push_chars(stream,UC"HTTP/1.1 ");
		jbl_stream_push_uint(stream,head->status);
		switch(head->status)
		{
			case 101:	jbl_stream_push_chars(stream,UC" Switching Protocols")	;break;
			case 200:	jbl_stream_push_chars(stream,UC" OK")				;break;
			case 206:	jbl_stream_push_chars(stream,UC" Partial Content")	;break;
			case 304:	jbl_stream_push_chars(stream,UC" Not Modified")		;break;
			case 404:	jbl_stream_push_chars(stream,UC" Not Found")		;break;
			case 416:	jbl_stream_push_chars(stream,UC" Range Not Satisfiable")		;break;
		}
	}
	else
	{
		char * method		[]={"","GET ","POST "};
		char * protocol		[]={""," HTTP/1.1",""};
		jbl_stream_push_chars	(stream,UC method[head->method]);
		jbl_stream_push_string	(stream,head->url);
		if(head->parameter)
		{
			jbl_stream_push_char(stream,'?');
			jbl_uint8 f=0;
			jbl_ht_foreach(head->parameter,i)
			{
				if(f)jbl_stream_push_char(stream,'&');
				f=1;
				jbl_stream_push_string(stream,i->k);
				jbl_stream_push_char(stream,'=');
				if(Vis_jbl_string(i->v))jbl_stream_push_string(stream,jbl_Vstring(i->v));
				else					jbl_var_json_put(i->v,stream,0,0);
			}		
		}		
		jbl_stream_push_chars	(stream,UC protocol[head->protocol]);
	}
	rn();
	if(head->cache==JWL_HTTP_CACHE_MAX_AGE)
	{
		jbl_stream_push_chars(stream,UC"Cache-Control: max-age=")	,jbl_stream_push_uint(stream,head->cache_max_age)				,rn();
		jbl_time * t=jbl_time_add_second(jbl_time_now(NULL),head->cache_max_age);
//		jbl_stream_push_chars(stream,UC"Date: ")	,jbl_time_to_string_format(t,stream,UC JBL_TIME_FORMAT_RFC1123)					,rn();
//		jbl_stream_push_chars(stream,UC"Expires: ")	,jbl_time_to_string_format(t,stream,UC JBL_TIME_FORMAT_RFC1123)					,rn();
		t=jbl_time_free(t);
	}
	else
	{
		jbl_stream_push_chars(stream,UC"Pragma: no-cache")																			,rn();
		jbl_stream_push_chars(stream,UC"Cache-Control: no-cache")																	,rn();
	}
	if(head->connection)
	{
		char * connection[]={"","keep-alive","close","Upgrade"};
		jbl_uint8 f=0;
		jbl_stream_push_chars(stream,UC"Connection: ");
		if(head->connection&JWL_HTTP_CONNECTION_KEEP_ALIVE	){jbl_stream_push_chars(stream,UC connection[1]);f=1;}
		if(head->connection&JWL_HTTP_CONNECTION_CLOSE		){if(f)jbl_stream_push_chars(stream,UC", ");jbl_stream_push_chars(stream,UC connection[2]);f=1;}
		if(head->connection&JWL_HTTP_CONNECTION_UPGRADE		){if(f)jbl_stream_push_chars(stream,UC", ");jbl_stream_push_chars(stream,UC connection[3]);f=1;}
		rn();
	}
	if(head->etag&&jwl_http_head_is_response(head))
		jbl_stream_push_chars(stream,UC"ETag: ")							,jbl_stream_push_string(stream,head->etag)				,rn();
	if(head->etag&&jwl_http_head_is_request(head))
		jbl_stream_push_chars(stream,UC"If-None-Match: ")					,jbl_stream_push_string(stream,head->etag)				,rn();
	if(head->content_type)
	{
		jbl_stream_push_chars(stream,UC"Content-Type: ")					,jbl_stream_push_chars(stream,jbl_file_get_ct_chars_by_ctid(head->content_type));
		char *charset[]={"","UTF-8"};
		if(head->charset)
			jbl_stream_push_chars(stream,UC"; charset=")					,jbl_stream_push_chars(stream,UC charset[head->charset]);
		rn();
	}
	if(head->status==206&&jwl_http_head_is_response(head))
	{
		jbl_stream_push_chars(stream,UC"Content-Length: ")					,jbl_stream_push_uint(stream,(head->range.end?head->range.end:size)-head->range.start)	,rn();//注意，range是闭区间，而jwl,jbl要求左闭右开区间
		jbl_stream_push_chars(stream,UC"Content-Range: bytes ")				,jbl_stream_push_uint(stream,head->range.start)			,jbl_stream_push_char(stream,'-')	,jbl_stream_push_uint(stream,head->range.end?(head->range.end-1):0)	,jbl_stream_push_char(stream,'/')	,jbl_stream_push_uint(stream,size)	,rn();
	}
	else
		jbl_stream_push_chars(stream,UC"Content-Length: ")					,jbl_stream_push_uint(stream,size)						,rn();
	if(head->host&&jwl_http_head_is_request(head))
		jbl_stream_push_chars(stream,UC"Host: ")							,jbl_stream_push_string(stream,head->host)				,rn();	
	
	
	if(jwl_http_head_is_response(head))
	{
		jbl_stream_push_chars(stream,UC"Server: "JWL_HTTP_RESPONSE_SERVER_NAME)														,rn();
		jbl_stream_push_chars(stream,UC"Accept-Ranges: bytes")																			,rn();
		if(head->connection==JWL_HTTP_CONNECTION_UPGRADE&&head->upgrade)
		{
			char * upgrade[]={"","websocket"};
			jbl_stream_push_chars(stream,UC"Upgrade: ")							,jbl_stream_push_chars(stream,UC upgrade[head->upgrade])		,rn();
		}
			
		if(head->filename)
		{
			jbl_stream_push_chars(stream,UC"Content-Disposition: attachment; filename=\"");
			jbl_stream_push_string(stream,head->filename);
			jbl_stream_push_char(stream,'"');
			rn();
		}
	}
	if(head->v)
		jbl_ht_foreach(head->v,i)
		{
			jbl_stream_push_string(stream,jbl_htk(i));
			jbl_stream_push_chars(stream,UC": ");
			if(Vis_jbl_string(i->v))jbl_stream_push_string(stream,jbl_Vstring(i->v));
			else					jbl_var_json_put(i->v,stream,0,0);
			rn();
		}
	rn();
#undef rn
}
#line 301 "jwl/jwl_http.c"
enum jwl_http_scanner_condition {
	jwl_http_scanner_condition_0,
	jwl_http_scanner_condition_start,
	jwl_http_scanner_condition_starts,
	jwl_http_scanner_condition_status,
	jwl_http_scanner_condition_statuse,
	jwl_http_scanner_condition_url,
	jwl_http_scanner_condition_parameter,
	jwl_http_scanner_condition_parameterv,
	jwl_http_scanner_condition_protocol,
	jwl_http_scanner_condition_head_body,
	jwl_http_scanner_condition_head_host,
	jwl_http_scanner_condition_head_ua,
	jwl_http_scanner_condition_head_refer,
	jwl_http_scanner_condition_head_etag,
	jwl_http_scanner_condition_head_conn,
	jwl_http_scanner_condition_head_upgrade,
	jwl_http_scanner_condition_head_range_s,
	jwl_http_scanner_condition_head_range_e,
	jwl_http_scanner_condition_head_accept,
	jwl_http_scanner_condition_head_acen,
	jwl_http_scanner_condition_head_aclan,
	jwl_http_scanner_condition_head_cookie,
	jwl_http_scanner_condition_head_cookiev,
	jwl_http_scanner_condition_head_cache,
	jwl_http_scanner_condition_special_key,
	jwl_http_scanner_condition_special_var,
};
#line 298 "jwl/jwl_http.l"


jwl_http_head* jwl_http_head_decode(jbl_string *buf,jbl_string_size_type *start)
{	
	if(!buf)return NULL;
	buf=jbl_refer_pull(buf);
	if(!buf->len)return NULL;
	jwl_http_head * head=jwl_http_head_new();
	head=jwl_http_head_set_request(head);
	unsigned char	*	YYMARKER;
	unsigned char	*	YYCURSOR=buf->s+(start?(*start):0);
	jbl_string		*	tmp_key	=NULL;
	jbl_var			*	tmp_var	=NULL;
	#define YYCTYPE		unsigned char

#line 346 "jwl/jwl_http.c"
{
	YYCTYPE yych;
	switch (head->cond) {
	case jwl_http_scanner_condition_0: goto yyc_0;
	case jwl_http_scanner_condition_start: goto yyc_start;
	case jwl_http_scanner_condition_starts: goto yyc_starts;
	case jwl_http_scanner_condition_status: goto yyc_status;
	case jwl_http_scanner_condition_statuse: goto yyc_statuse;
	case jwl_http_scanner_condition_url: goto yyc_url;
	case jwl_http_scanner_condition_parameter: goto yyc_parameter;
	case jwl_http_scanner_condition_parameterv: goto yyc_parameterv;
	case jwl_http_scanner_condition_protocol: goto yyc_protocol;
	case jwl_http_scanner_condition_head_body: goto yyc_head_body;
	case jwl_http_scanner_condition_head_host: goto yyc_head_host;
	case jwl_http_scanner_condition_head_ua: goto yyc_head_ua;
	case jwl_http_scanner_condition_head_refer: goto yyc_head_refer;
	case jwl_http_scanner_condition_head_etag: goto yyc_head_etag;
	case jwl_http_scanner_condition_head_conn: goto yyc_head_conn;
	case jwl_http_scanner_condition_head_upgrade: goto yyc_head_upgrade;
	case jwl_http_scanner_condition_head_range_s: goto yyc_head_range_s;
	case jwl_http_scanner_condition_head_range_e: goto yyc_head_range_e;
	case jwl_http_scanner_condition_head_accept: goto yyc_head_accept;
	case jwl_http_scanner_condition_head_acen: goto yyc_head_acen;
	case jwl_http_scanner_condition_head_aclan: goto yyc_head_aclan;
	case jwl_http_scanner_condition_head_cookie: goto yyc_head_cookie;
	case jwl_http_scanner_condition_head_cookiev: goto yyc_head_cookiev;
	case jwl_http_scanner_condition_head_cache: goto yyc_head_cache;
	case jwl_http_scanner_condition_special_key: goto yyc_special_key;
	case jwl_http_scanner_condition_special_var: goto yyc_special_var;
	}
/* *********************************** */
yyc_0:
	head->cond = (jwl_http_scanner_condition_start);
	goto yyc_start;
/* *********************************** */
yyc_start:
	yych = *YYCURSOR;
	switch (yych) {
	case ' ':	goto yy7;
	case 'G':	goto yy9;
	case 'H':	goto yy10;
	case 'P':	goto yy11;
	default:	goto yy6;
	}
yy6:
yy7:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_url);
#line 324 "jwl/jwl_http.l"
	{head->url				=jbl_string_free    (head->url)									;goto yyc_url;}
#line 397 "jwl/jwl_http.c"
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':	goto yy12;
	default:	goto yy6;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy13;
	default:	goto yy6;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy14;
	default:	goto yy6;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy15;
	default:	goto yy6;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy17;
	default:	goto yy6;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy18;
	default:	goto yy6;
	}
yy15:
	++YYCURSOR;
#line 322 "jwl/jwl_http.l"
	{head->method=JWL_HTTP_METHOD_GET		;head=jwl_http_head_set_request(head)			;goto yyc_start;}
#line 438 "jwl/jwl_http.c"
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':	goto yy19;
	default:	goto yy6;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy20;
	default:	goto yy6;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
	case '/':	goto yy22;
	default:	goto yy6;
	}
yy20:
	++YYCURSOR;
#line 321 "jwl/jwl_http.l"
	{head->method=JWL_HTTP_METHOD_POST		;head=jwl_http_head_set_request(head)			;goto yyc_start;}
#line 461 "jwl/jwl_http.c"
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':	goto yy23;
	default:	goto yy6;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy24;
	default:	goto yy6;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':	goto yy25;
	default:	goto yy6;
	}
yy25:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_starts);
#line 323 "jwl/jwl_http.l"
	{head->method=JWL_HTTP_METHOD_GET		;head=jwl_http_head_set_response(head)			;goto yyc_starts;}
#line 485 "jwl/jwl_http.c"
/* *********************************** */
yyc_starts:
	yych = *YYCURSOR;
	switch (yych) {
	case ' ':	goto yy30;
	default:	goto yy29;
	}
yy29:
yy30:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_status);
#line 325 "jwl/jwl_http.l"
	{head->status			=0																;goto yyc_status;}
#line 499 "jwl/jwl_http.c"
/* *********************************** */
yyc_status:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy35;
	case ' ':	goto yy37;
	default:	goto yy34;
	}
yy34:
#line 327 "jwl/jwl_http.l"
	{head->status			=((head->status<<3)+(head->status<<1)+*YYCURSOR-'0')			;++YYCURSOR;goto yyc_status;}
#line 511 "jwl/jwl_http.c"
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy39;
	default:	goto yy36;
	}
yy36:
	YYCURSOR = YYMARKER;
	goto yy34;
yy37:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_statuse);
#line 328 "jwl/jwl_http.l"
	{																						;goto yyc_statuse;}
#line 526 "jwl/jwl_http.c"
yy39:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 329 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 532 "jwl/jwl_http.c"
/* *********************************** */
yyc_statuse:
	yych = *YYCURSOR;
	switch (yych) {
	case '\r':	goto yy44;
	default:	goto yy43;
	}
yy43:
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy45;
	default:	goto yy43;
	}
yy45:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 330 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 552 "jwl/jwl_http.c"
/* *********************************** */
yyc_url:
	yych = *YYCURSOR;
	switch (yych) {
	case ' ':	goto yy50;
	case '?':	goto yy52;
	default:	goto yy49;
	}
yy49:
#line 332 "jwl/jwl_http.l"
	{head->url				=jbl_string_add_char(head->url,*YYCURSOR)						;++YYCURSOR;goto yyc_url;}
#line 564 "jwl/jwl_http.c"
yy50:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_protocol);
#line 333 "jwl/jwl_http.l"
	{																						;goto yyc_protocol;}
#line 570 "jwl/jwl_http.c"
yy52:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_parameter);
#line 334 "jwl/jwl_http.l"
	{tmp_key				=jbl_string_free    (tmp_key)									;goto yyc_parameter;}
#line 576 "jwl/jwl_http.c"
/* *********************************** */
yyc_parameter:
	yych = *YYCURSOR;
	switch (yych) {
	case ' ':	goto yy57;
	case '&':	goto yy59;
	case '=':	goto yy61;
	default:	goto yy56;
	}
yy56:
#line 335 "jwl/jwl_http.l"
	{tmp_key				=jbl_string_add_char(tmp_key,*YYCURSOR)		;++YYCURSOR;		;goto yyc_parameter;}
#line 589 "jwl/jwl_http.c"
yy57:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_protocol);
#line 336 "jwl/jwl_http.l"
	{tmp_key=jbl_string_free(tmp_key);tmp_var=jbl_var_free(tmp_var);						;goto yyc_protocol;}
#line 595 "jwl/jwl_http.c"
yy59:
	++YYCURSOR;
#line 337 "jwl/jwl_http.l"
	{tmp_key=jbl_string_free(tmp_key);tmp_var=jbl_var_free(tmp_var);						;goto yyc_parameter;}
#line 600 "jwl/jwl_http.c"
yy61:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_parameterv);
#line 338 "jwl/jwl_http.l"
	{tmp_var				=jbl_var_free(tmp_var)			;tmp_var=jbl_Vstring_new();														;goto yyc_parameterv;}
#line 606 "jwl/jwl_http.c"
/* *********************************** */
yyc_parameterv:
	yych = *YYCURSOR;
	switch (yych) {
	case ' ':	goto yy66;
	case '&':	goto yy68;
	default:	goto yy65;
	}
yy65:
#line 339 "jwl/jwl_http.l"
	{tmp_var				=jbl_V(jbl_string_add_char(jbl_Vstring(tmp_var),*YYCURSOR))		;++YYCURSOR;goto yyc_parameterv;}
#line 618 "jwl/jwl_http.c"
yy66:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_protocol);
#line 341 "jwl/jwl_http.l"
	{head->parameter		=jbl_ht_insert(head->parameter,tmp_key,tmp_var);tmp_key=jbl_string_free(tmp_key);tmp_var=jbl_var_free(tmp_var);			;goto yyc_protocol;}
#line 624 "jwl/jwl_http.c"
yy68:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 340 "jwl/jwl_http.l"
	{head->parameter		=jbl_ht_insert(head->parameter,tmp_key,tmp_var);tmp_key=jbl_string_free(tmp_key);tmp_var=jbl_var_free(tmp_var);			;goto yyc_parameter;}
#line 630 "jwl/jwl_http.c"
/* *********************************** */
yyc_protocol:
	yych = *YYCURSOR;
	switch (yych) {
	case '\r':	goto yy73;
	case 'H':	goto yy74;
	default:	goto yy72;
	}
yy72:
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy75;
	default:	goto yy72;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy77;
	default:	goto yy72;
	}
yy75:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 344 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 657 "jwl/jwl_http.c"
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy78;
	default:	goto yy72;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':	goto yy79;
	default:	goto yy72;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case '/':	goto yy80;
	default:	goto yy72;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':	goto yy81;
	default:	goto yy72;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy82;
	default:	goto yy72;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':	goto yy83;
	default:	goto yy72;
	}
yy83:
	++YYCURSOR;
#line 343 "jwl/jwl_http.l"
	{head->protocol			=JWL_HTTP_PROTOCOL_HTTP_1_1										;goto yyc_protocol;}
#line 698 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_body:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy88;
	case '\r':	goto yy90;
	case 'A':	goto yy92;
	case 'C':	goto yy93;
	case 'E':	goto yy94;
	case 'H':	goto yy95;
	case 'I':	goto yy96;
	case 'P':	goto yy97;
	case 'R':	goto yy98;
	case 'U':	goto yy99;
	default:	goto yy87;
	}
yy87:
	head->cond = (jwl_http_scanner_condition_special_key);
#line 411 "jwl/jwl_http.l"
	{tmp_key				=jbl_string_free    (tmp_key)	;tmp_key=jbl_string_add_char(tmp_key,*YYCURSOR)		;++YYCURSOR;		;goto yyc_special_key;}
#line 719 "jwl/jwl_http.c"
yy88:
	++YYCURSOR;
#line 419 "jwl/jwl_http.l"
	{if(start)*start=YYCURSOR-buf->s;return head;}
#line 724 "jwl/jwl_http.c"
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy100;
	default:	goto yy91;
	}
yy91:
	YYCURSOR = YYMARKER;
	goto yy87;
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy102;
	default:	goto yy91;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy103;
	case 'o':	goto yy104;
	default:	goto yy91;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy105;
	default:	goto yy91;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy106;
	default:	goto yy91;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy107;
	default:	goto yy91;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy108;
	default:	goto yy91;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy109;
	case 'e':	goto yy110;
	default:	goto yy91;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy111;
	case 's':	goto yy112;
	default:	goto yy91;
	}
yy100:
	++YYCURSOR;
#line 418 "jwl/jwl_http.l"
	{if(start)*start=YYCURSOR-buf->s;return head;}
#line 789 "jwl/jwl_http.c"
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy113;
	default:	goto yy91;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy114;
	default:	goto yy91;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy115;
	case 'o':	goto yy116;
	default:	goto yy91;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy117;
	default:	goto yy91;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy118;
	default:	goto yy91;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy119;
	default:	goto yy91;
	}
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy120;
	default:	goto yy91;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy121;
	default:	goto yy91;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy122;
	default:	goto yy91;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy123;
	default:	goto yy91;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy124;
	default:	goto yy91;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy125;
	default:	goto yy91;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy126;
	default:	goto yy91;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy127;
	default:	goto yy91;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy128;
	default:	goto yy91;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy129;
	default:	goto yy91;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy130;
	default:	goto yy91;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':	goto yy131;
	default:	goto yy91;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy132;
	default:	goto yy91;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy133;
	default:	goto yy91;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy134;
	default:	goto yy91;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy135;
	default:	goto yy91;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy136;
	default:	goto yy91;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy137;
	default:	goto yy91;
	}
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy138;
	default:	goto yy91;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy139;
	default:	goto yy91;
	}
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy140;
	default:	goto yy91;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy141;
	default:	goto yy91;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy142;
	default:	goto yy91;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy143;
	default:	goto yy91;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy144;
	default:	goto yy91;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy145;
	default:	goto yy91;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy146;
	default:	goto yy91;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy147;
	default:	goto yy91;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy148;
	default:	goto yy91;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy149;
	default:	goto yy91;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy150;
	default:	goto yy91;
	}
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy151;
	default:	goto yy91;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy152;
	default:	goto yy91;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy153;
	default:	goto yy91;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy155;
	default:	goto yy91;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy157;
	default:	goto yy91;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy158;
	default:	goto yy91;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy159;
	default:	goto yy91;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy160;
	default:	goto yy91;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy161;
	default:	goto yy91;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':	goto yy162;
	default:	goto yy91;
	}
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy163;
	case ':':	goto yy164;
	default:	goto yy91;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy165;
	default:	goto yy91;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy166;
	default:	goto yy91;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy167;
	default:	goto yy91;
	}
yy153:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_etag);
#line 358 "jwl/jwl_http.l"
	{head->etag				=jbl_string_free    (head->etag)								;goto yyc_head_etag;}
#line 1103 "jwl/jwl_http.c"
yy155:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_host);
#line 346 "jwl/jwl_http.l"
	{head->host				=jbl_string_free    (head->host)								;goto yyc_head_host;}
#line 1109 "jwl/jwl_http.c"
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy168;
	default:	goto yy91;
	}
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy169;
	default:	goto yy91;
	}
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy170;
	default:	goto yy91;
	}
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy171;
	default:	goto yy91;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy172;
	default:	goto yy91;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy173;
	default:	goto yy91;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':	goto yy174;
	case 'L':	goto yy175;
	default:	goto yy91;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy176;
	default:	goto yy91;
	}
yy165:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy178;
	default:	goto yy91;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy179;
	default:	goto yy91;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy180;
	default:	goto yy91;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy182;
	default:	goto yy91;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy183;
	default:	goto yy91;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy185;
	default:	goto yy91;
	}
yy171:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy186;
	default:	goto yy91;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy187;
	default:	goto yy91;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy188;
	default:	goto yy91;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy189;
	default:	goto yy91;
	}
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy190;
	default:	goto yy91;
	}
yy176:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_accept);
#line 381 "jwl/jwl_http.l"
	{																						;goto yyc_head_accept;}
#line 1230 "jwl/jwl_http.c"
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy191;
	default:	goto yy91;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy192;
	default:	goto yy91;
	}
yy180:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_cookie);
#line 393 "jwl/jwl_http.l"
	{tmp_key				=jbl_string_free    (tmp_key)	;								;goto yyc_head_cookie;}
#line 1248 "jwl/jwl_http.c"
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy193;
	default:	goto yy91;
	}
yy183:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_cache);
#line 405 "jwl/jwl_http.l"
	{																						;goto yyc_head_cache;}
#line 1260 "jwl/jwl_http.c"
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy194;
	default:	goto yy91;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy195;
	default:	goto yy91;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy197;
	default:	goto yy91;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy199;
	default:	goto yy91;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy200;
	default:	goto yy91;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy201;
	default:	goto yy91;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy202;
	default:	goto yy91;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy203;
	default:	goto yy91;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy204;
	default:	goto yy91;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy205;
	default:	goto yy91;
	}
yy195:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_refer);
#line 354 "jwl/jwl_http.l"
	{head->referer			=jbl_string_free    (head->referer)								;goto yyc_head_refer;}
#line 1326 "jwl/jwl_http.c"
yy197:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_upgrade);
#line 370 "jwl/jwl_http.l"
	{																						;goto yyc_head_upgrade;}
#line 1332 "jwl/jwl_http.c"
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy206;
	default:	goto yy91;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy207;
	default:	goto yy91;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy208;
	default:	goto yy91;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy209;
	default:	goto yy91;
	}
yy203:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy210;
	default:	goto yy91;
	}
yy204:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy211;
	default:	goto yy91;
	}
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy212;
	default:	goto yy91;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy213;
	default:	goto yy91;
	}
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy214;
	default:	goto yy91;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy215;
	default:	goto yy91;
	}
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy216;
	default:	goto yy91;
	}
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy217;
	default:	goto yy91;
	}
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy219;
	default:	goto yy91;
	}
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy220;
	default:	goto yy91;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy221;
	default:	goto yy91;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy223;
	default:	goto yy91;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy224;
	default:	goto yy91;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy225;
	default:	goto yy91;
	}
yy217:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_conn);
#line 363 "jwl/jwl_http.l"
	{																						;goto yyc_head_conn;}
#line 1446 "jwl/jwl_http.c"
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy226;
	default:	goto yy91;
	}
yy220:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy227;
	default:	goto yy91;
	}
yy221:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_ua);
#line 350 "jwl/jwl_http.l"
	{head->ua				=jbl_string_free    (head->ua)									;goto yyc_head_ua;}
#line 1464 "jwl/jwl_http.c"
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy229;
	default:	goto yy91;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy230;
	default:	goto yy91;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy231;
	default:	goto yy91;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy232;
	default:	goto yy91;
	}
yy227:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_range_s);
#line 374 "jwl/jwl_http.l"
	{head->range.start		=0																;goto yyc_head_range_s;}
#line 1494 "jwl/jwl_http.c"
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy233;
	default:	goto yy91;
	}
yy230:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy234;
	default:	goto yy91;
	}
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy235;
	default:	goto yy91;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy237;
	default:	goto yy91;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy239;
	default:	goto yy91;
	}
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy240;
	default:	goto yy91;
	}
yy235:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_cache);
#line 404 "jwl/jwl_http.l"
	{																						;goto yyc_head_cache;}
#line 1536 "jwl/jwl_http.c"
yy237:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_etag);
#line 359 "jwl/jwl_http.l"
	{head->etag				=jbl_string_free    (head->etag)								;goto yyc_head_etag;}
#line 1542 "jwl/jwl_http.c"
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy241;
	default:	goto yy91;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy243;
	default:	goto yy91;
	}
yy241:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_acen);
#line 385 "jwl/jwl_http.l"
	{																						;goto yyc_head_acen;}
#line 1560 "jwl/jwl_http.c"
yy243:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_aclan);
#line 389 "jwl/jwl_http.l"
	{																						;goto yyc_head_aclan;}
#line 1566 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_host:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy248;
	default:	goto yy247;
	}
yy247:
#line 347 "jwl/jwl_http.l"
	{head->host				=jbl_string_add_char(head->host,*YYCURSOR)						;++YYCURSOR;goto yyc_head_host;}
#line 1577 "jwl/jwl_http.c"
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy250;
	default:	goto yy249;
	}
yy249:
	YYCURSOR = YYMARKER;
	goto yy247;
yy250:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 348 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 1592 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_ua:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy255;
	default:	goto yy254;
	}
yy254:
#line 351 "jwl/jwl_http.l"
	{head->ua				=jbl_string_add_char(head->ua,*YYCURSOR)						;++YYCURSOR;goto yyc_head_ua;}
#line 1603 "jwl/jwl_http.c"
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy257;
	default:	goto yy256;
	}
yy256:
	YYCURSOR = YYMARKER;
	goto yy254;
yy257:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 352 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 1618 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_refer:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy262;
	default:	goto yy261;
	}
yy261:
#line 355 "jwl/jwl_http.l"
	{head->referer			=jbl_string_add_char(head->referer,*YYCURSOR)					;++YYCURSOR;goto yyc_head_refer;}
#line 1629 "jwl/jwl_http.c"
yy262:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy264;
	default:	goto yy263;
	}
yy263:
	YYCURSOR = YYMARKER;
	goto yy261;
yy264:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 356 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 1644 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_etag:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy269;
	default:	goto yy268;
	}
yy268:
#line 360 "jwl/jwl_http.l"
	{head->etag				=jbl_string_add_char(head->etag,*YYCURSOR)						;++YYCURSOR;goto yyc_head_etag;}
#line 1655 "jwl/jwl_http.c"
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy271;
	default:	goto yy270;
	}
yy270:
	YYCURSOR = YYMARKER;
	goto yy268;
yy271:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 361 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 1670 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_conn:
	yych = *YYCURSOR;
	switch (yych) {
	case '\r':	goto yy276;
	case ',':	goto yy277;
	case 'U':	goto yy278;
	case 'c':	goto yy279;
	case 'k':	goto yy280;
	case 'n':	goto yy281;
	default:	goto yy275;
	}
yy275:
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy282;
	default:	goto yy275;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy284;
	default:	goto yy275;
	}
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy286;
	default:	goto yy275;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy287;
	default:	goto yy275;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy288;
	default:	goto yy275;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy289;
	default:	goto yy275;
	}
yy282:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 368 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 1725 "jwl/jwl_http.c"
yy284:
	++YYCURSOR;
#line 367 "jwl/jwl_http.l"
	{																						;goto yyc_head_conn;}
#line 1730 "jwl/jwl_http.c"
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy290;
	default:	goto yy275;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy291;
	default:	goto yy275;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy292;
	default:	goto yy275;
	}
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy293;
	default:	goto yy275;
	}
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy294;
	default:	goto yy275;
	}
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy295;
	default:	goto yy275;
	}
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy296;
	default:	goto yy275;
	}
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy297;
	default:	goto yy275;
	}
yy294:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy298;
	default:	goto yy275;
	}
yy295:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy299;
	default:	goto yy275;
	}
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy301;
	default:	goto yy275;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy302;
	default:	goto yy275;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy303;
	default:	goto yy275;
	}
yy299:
	++YYCURSOR;
#line 365 "jwl/jwl_http.l"
	{head->connection		|=JWL_HTTP_CONNECTION_CLOSE										;goto yyc_head_conn;}
#line 1813 "jwl/jwl_http.c"
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy304;
	default:	goto yy275;
	}
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy305;
	default:	goto yy275;
	}
yy303:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy306;
	default:	goto yy275;
	}
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy308;
	default:	goto yy275;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy309;
	default:	goto yy275;
	}
yy306:
	++YYCURSOR;
#line 366 "jwl/jwl_http.l"
	{head->connection		|=JWL_HTTP_CONNECTION_UPGRADE									;goto yyc_head_conn;}
#line 1848 "jwl/jwl_http.c"
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy310;
	default:	goto yy275;
	}
yy309:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy311;
	default:	goto yy275;
	}
yy310:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy313;
	default:	goto yy275;
	}
yy311:
	++YYCURSOR;
#line 406 "jwl/jwl_http.l"
	{head->cache			=JWL_HTTP_CACHE_NO												;goto yyc_head_cache;}
#line 1871 "jwl/jwl_http.c"
yy313:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy314;
	default:	goto yy275;
	}
yy314:
	++YYCURSOR;
#line 364 "jwl/jwl_http.l"
	{head->connection		|=JWL_HTTP_CONNECTION_KEEP_ALIVE								;goto yyc_head_conn;}
#line 1882 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_upgrade:
	yych = *YYCURSOR;
	switch (yych) {
	case '\r':	goto yy319;
	case 'w':	goto yy320;
	default:	goto yy318;
	}
yy318:
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy321;
	default:	goto yy318;
	}
yy320:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy323;
	default:	goto yy318;
	}
yy321:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 372 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 1909 "jwl/jwl_http.c"
yy323:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy324;
	default:	goto yy318;
	}
yy324:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy325;
	default:	goto yy318;
	}
yy325:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy326;
	default:	goto yy318;
	}
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy327;
	default:	goto yy318;
	}
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy328;
	default:	goto yy318;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy329;
	default:	goto yy318;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy330;
	default:	goto yy318;
	}
yy330:
	++YYCURSOR;
#line 371 "jwl/jwl_http.l"
	{head->upgrade			=JWL_HTTP_UPGRADE_WEBSOCKET										;goto yyc_head_upgrade;}
#line 1956 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_range_s:
	yych = *YYCURSOR;
	switch (yych) {
	case '\r':	goto yy335;
	case '-':	goto yy336;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy338;
	default:	goto yy334;
	}
yy334:
yy335:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy340;
	default:	goto yy334;
	}
yy336:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_range_e);
#line 375 "jwl/jwl_http.l"
	{head->range.end		=0																;goto yyc_head_range_e;}
#line 1987 "jwl/jwl_http.c"
yy338:
	++YYCURSOR;
#line 376 "jwl/jwl_http.l"
	{head->range.start		=(head->range.start<<3)+(head->range.start<<1)+*(YYCURSOR-1)-'0';goto yyc_head_range_s;}
#line 1992 "jwl/jwl_http.c"
yy340:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 377 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 1998 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_range_e:
	yych = *YYCURSOR;
	switch (yych) {
	case '\r':	goto yy345;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy346;
	default:	goto yy344;
	}
yy344:
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy348;
	default:	goto yy344;
	}
yy346:
	++YYCURSOR;
#line 378 "jwl/jwl_http.l"
	{head->range.end		=(head->range.end<<3)+(head->range.end<<1)+*(YYCURSOR-1)-'0'	;goto yyc_head_range_e;}
#line 2027 "jwl/jwl_http.c"
yy348:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 379 "jwl/jwl_http.l"
	{head->range.end		=(head->range.end)?(head->range.end+1):0						;goto yyc_head_body;}
#line 2033 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_accept:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy353;
	default:	goto yy352;
	}
yy352:
#line 382 "jwl/jwl_http.l"
	{																						;++YYCURSOR;goto yyc_head_accept;}
#line 2044 "jwl/jwl_http.c"
yy353:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy355;
	default:	goto yy354;
	}
yy354:
	YYCURSOR = YYMARKER;
	goto yy352;
yy355:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 383 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 2059 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_acen:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy360;
	default:	goto yy359;
	}
yy359:
#line 386 "jwl/jwl_http.l"
	{																						;++YYCURSOR;goto yyc_head_acen;}
#line 2070 "jwl/jwl_http.c"
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy362;
	default:	goto yy361;
	}
yy361:
	YYCURSOR = YYMARKER;
	goto yy359;
yy362:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 387 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 2085 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_aclan:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy367;
	default:	goto yy366;
	}
yy366:
#line 390 "jwl/jwl_http.l"
	{																						;++YYCURSOR;goto yyc_head_aclan;}
#line 2096 "jwl/jwl_http.c"
yy367:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy369;
	default:	goto yy368;
	}
yy368:
	YYCURSOR = YYMARKER;
	goto yy366;
yy369:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 391 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 2111 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_cookie:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy374;
	case '=':	goto yy376;
	default:	goto yy373;
	}
yy373:
#line 394 "jwl/jwl_http.l"
	{tmp_key				=jbl_string_add_char(tmp_key,*YYCURSOR)		;++YYCURSOR;		;goto yyc_head_cookie;}
#line 2123 "jwl/jwl_http.c"
yy374:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy378;
	default:	goto yy375;
	}
yy375:
	YYCURSOR = YYMARKER;
	goto yy373;
yy376:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_cookiev);
#line 395 "jwl/jwl_http.l"
	{tmp_var				=jbl_var_free(tmp_var)			;tmp_var=jbl_Vstring_new()		;goto yyc_head_cookiev;}
#line 2138 "jwl/jwl_http.c"
yy378:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 396 "jwl/jwl_http.l"
	{tmp_key				=jbl_string_free    (tmp_key)	;								;goto yyc_head_body;}
#line 2144 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_cookiev:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy383;
	case ';':	goto yy385;
	default:	goto yy382;
	}
yy382:
#line 397 "jwl/jwl_http.l"
	{tmp_var				=jbl_V(jbl_string_add_char(jbl_Vstring(tmp_var),*YYCURSOR))		;++YYCURSOR;goto yyc_head_cookiev;}
#line 2156 "jwl/jwl_http.c"
yy383:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy386;
	default:	goto yy384;
	}
yy384:
	YYCURSOR = YYMARKER;
	goto yy382;
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy388;
	default:	goto yy384;
	}
yy386:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 399 "jwl/jwl_http.l"
	{head->cookie			=jbl_ht_insert(head->cookie,tmp_key,tmp_var);tmp_key=jbl_string_free(tmp_key);tmp_var=jbl_var_free(tmp_var);			;goto yyc_head_body;}
#line 2177 "jwl/jwl_http.c"
yy388:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_cookie);
#line 398 "jwl/jwl_http.l"
	{head->cookie			=jbl_ht_insert(head->cookie,tmp_key,tmp_var);tmp_key=jbl_string_free(tmp_key);tmp_var=jbl_var_free(tmp_var);			;goto yyc_head_cookie;}
#line 2183 "jwl/jwl_http.c"
/* *********************************** */
yyc_head_cache:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy393;
	default:	goto yy392;
	}
yy392:
#line 407 "jwl/jwl_http.l"
	{																						;++YYCURSOR;goto yyc_head_cache;}
#line 2194 "jwl/jwl_http.c"
yy393:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy395;
	default:	goto yy394;
	}
yy394:
	YYCURSOR = YYMARKER;
	goto yy392;
yy395:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 408 "jwl/jwl_http.l"
	{																						;goto yyc_head_body;}
#line 2209 "jwl/jwl_http.c"
/* *********************************** */
yyc_special_key:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy400;
	case ':':	goto yy402;
	default:	goto yy399;
	}
yy399:
#line 412 "jwl/jwl_http.l"
	{tmp_key				=jbl_string_add_char(tmp_key,*YYCURSOR)		;++YYCURSOR;					;goto yyc_special_key;}
#line 2221 "jwl/jwl_http.c"
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy403;
	default:	goto yy401;
	}
yy401:
	YYCURSOR = YYMARKER;
	goto yy399;
yy402:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy405;
	default:	goto yy401;
	}
yy403:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 413 "jwl/jwl_http.l"
	{tmp_key				=jbl_string_free(tmp_key)	;tmp_var=jbl_var_free(tmp_var);					;goto yyc_head_body;}
#line 2242 "jwl/jwl_http.c"
yy405:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_special_var);
#line 414 "jwl/jwl_http.l"
	{tmp_var				=jbl_var_free(tmp_var)		;tmp_var=jbl_Vstring_new();						;goto yyc_special_var;}
#line 2248 "jwl/jwl_http.c"
/* *********************************** */
yyc_special_var:
	yych = *(YYMARKER = YYCURSOR);
	switch (yych) {
	case '\r':	goto yy410;
	default:	goto yy409;
	}
yy409:
#line 415 "jwl/jwl_http.l"
	{tmp_var				=jbl_V(jbl_string_add_char(jbl_Vstring(tmp_var),*YYCURSOR))		;++YYCURSOR	;goto yyc_special_var;}
#line 2259 "jwl/jwl_http.c"
yy410:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy412;
	default:	goto yy411;
	}
yy411:
	YYCURSOR = YYMARKER;
	goto yy409;
yy412:
	++YYCURSOR;
	head->cond = (jwl_http_scanner_condition_head_body);
#line 416 "jwl/jwl_http.l"
	{head->v				=jbl_ht_insert(head->v,tmp_key,tmp_var);tmp_key=jbl_string_free(tmp_key);tmp_var=jbl_var_free(tmp_var);			;goto yyc_head_body;}
#line 2274 "jwl/jwl_http.c"
}
#line 421 "jwl/jwl_http.l"

	#undef YYCTYPE	


	return head;
}


#if JBL_STREAM_ENABLE==1
jwl_http_head* jwl_http_head_view_put(jwl_http_head* this,jbl_stream *out,jbl_uint8 format,jbl_uint32 tabs,jbl_uint32 line,unsigned char * varname,unsigned char * func,unsigned char * file)
{
	jwl_http_head* thi;if(jbl_stream_view_put_format(thi=jbl_refer_pull(this),out,format,tabs,UC"jwl_http_head",line,varname,func,file)){jbl_stream_push_char(out,'\n');return this;}
	jbl_stream_push_char(out,'\n');
	++tabs;
	char * type			[]={"response","request"};
	char * charset		[]={"","UTF-8"};
	char * method		[]={"","get","post"};
	char * protocol		[]={"","HTTP/1.1"};
	char * connection	[]={"","keep alive","close","upgrade"};
	char * cache		[]={"","no","max age,"};
	char * upgrade		[]={"","websocket"};
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"type         :");jbl_stream_push_chars(out,UC type			[jwl_http_head_is_request(this)?1:0])	;jbl_stream_push_char(out,'\n');
	if(jwl_http_head_is_request(this))
	{
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"method       :");jbl_stream_push_chars(out,UC method		[thi->method])						;jbl_stream_push_char(out,'\n');	
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"url          :");jbl_stream_push_string(out,thi->url)											;jbl_stream_push_char(out,'\n');	
	}
	if(jwl_http_head_is_response(this))
	{
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"status       :");jbl_stream_push_uint(out,thi->status)											;jbl_stream_push_char(out,'\n');
	}
	
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"protocol     :");jbl_stream_push_chars(out,UC protocol		[thi->protocol])					;jbl_stream_push_char(out,'\n');	
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"charset      :");jbl_stream_push_chars(out,UC charset		[thi->charset])						;jbl_stream_push_char(out,'\n');
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"upgrade      :");jbl_stream_push_chars(out,UC upgrade		[thi->upgrade])						;jbl_stream_push_char(out,'\n');	
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"cache        :");jbl_stream_push_chars(out,UC cache		[thi->cache])						;if(thi->cache==JWL_HTTP_CACHE_MAX_AGE){jbl_stream_push_uint(out,thi->cache_max_age);}	;jbl_stream_push_char(out,'\n');	
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"range        :");jbl_stream_push_uint(out,thi->range.start)									;jbl_stream_push_char(out,'-' );	jbl_stream_push_uint(out,thi->range.end)			;jbl_stream_push_char(out,'\n');	
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"etag         :");jbl_stream_push_string(out,thi->etag)											;jbl_stream_push_char(out,'\n');
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"host         :");jbl_stream_push_string(out,thi->host)											;jbl_stream_push_char(out,'\n');	
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"content type :");jbl_stream_push_chars(out,jbl_file_get_ct_chars_by_ctid(thi->content_type))	;jbl_stream_push_char(out,'\n');
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"filename     :");jbl_stream_push_string(out,thi->filename)										;jbl_stream_push_char(out,'\n');
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"user agent   :");jbl_stream_push_string(out,thi->ua)											;jbl_stream_push_char(out,'\n');	
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"referer      :");jbl_stream_push_string(out,thi->referer)										;jbl_stream_push_char(out,'\n');
	for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"connection   :");
	if(!thi->connection)
		jbl_stream_push_chars(out,UC connection	[0]);
	else 
	{
		if(thi->connection&JWL_HTTP_CONNECTION_KEEP_ALIVE	)jbl_stream_push_chars(out,UC connection[1]),jbl_stream_push_char(out,',');
		if(thi->connection&JWL_HTTP_CONNECTION_CLOSE		)jbl_stream_push_chars(out,UC connection[2]),jbl_stream_push_char(out,',');
		if(thi->connection&JWL_HTTP_CONNECTION_UPGRADE		)jbl_stream_push_chars(out,UC connection[3]),jbl_stream_push_char(out,',');
	}
	jbl_stream_push_char(out,'\n');	
		

	if(thi->parameter)
	{
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"parameter    :");																				;jbl_stream_push_char(out,'\n');
		++tabs;
		jbl_ht_foreach(thi->parameter,i)
		{
			for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);//格式化的\t
			jbl_stream_push_string(out,i->k);
			for(jbl_int32 j=jbl_string_get_length(i->k);j<13;jbl_stream_push_char(out,' '),++j);//格式化的\t
			jbl_stream_push_char(out,':');
			if(Vis_jbl_string(i->v))jbl_stream_push_string(out,jbl_Vstring(i->v)),jbl_stream_push_char(out,'\n');	
			else					jbl_var_view_put(i->v,out,0,tabs,0,NULL,NULL,NULL);
		}		
		--tabs;
	}
	if(thi->cookie)
	{
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"cookie       :");																				;jbl_stream_push_char(out,'\n');
		++tabs;
		jbl_ht_foreach(thi->cookie,i)
		{
			for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);//格式化的\t
			jbl_stream_push_string(out,i->k);
			for(jbl_int32 j=jbl_string_get_length(i->k);j<13;jbl_stream_push_char(out,' '),++j);//格式化的\t
			jbl_stream_push_char(out,':');
			if(Vis_jbl_string(i->v))jbl_stream_push_string(out,jbl_Vstring(i->v)),jbl_stream_push_char(out,'\n');	
			else					jbl_var_view_put(i->v,out,0,tabs,0,NULL,NULL,NULL);
		}		
		--tabs;
	}
	if(thi->v)
		jbl_ht_foreach(thi->v,i)
		{
			for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);//格式化的\t
			jbl_stream_push_string(out,i->k);
			for(jbl_int32 j=jbl_string_get_length(i->k);j<13;jbl_stream_push_char(out,' '),++j);//格式化的\t
			jbl_stream_push_char(out,':');
			if(Vis_jbl_string(i->v))jbl_stream_push_string(out,jbl_Vstring(i->v)),jbl_stream_push_char(out,'\n');	
			else					jbl_var_view_put(i->v,out,0,tabs,0,NULL,NULL,NULL);
		}
	return this;
/*
	if(format){for(jbl_int32 i=0;i<tabs;jbl_stream_push_char(out,'\t'),++i);}
	jbl_stream_push_chars(out,UC"cache        :"),jbl_stream_push_uint(out,this->cache),jbl_stream_push_char(out,'\t');
	if(this->cache==JWL_HTTP_CACHE_MAX_AGE)
		jbl_stream_push_chars(out,UC"(max-age,"),jbl_stream_push_uint(out,this->cache_max_age),jbl_stream_push_chars(out,UC")\n");
	else
		jbl_stream_push_chars(out,UC"(no-cache)\n");
	jbl_stream_push_chars(out,UC"content type :"),jbl_stream_push_string(out,this->content_type),jbl_stream_push_char(out,'\n');
*/	
}
#endif




#endif
