/* Generated by re2c 1.3 on Tue Aug 11 16:10:51 2020 */
#line 1 "jwl/jwl_http.l"
/* Copyright (c) [2019] juruoyun developer team
   Juruoyun web lib is licensed under the Mulan PSL v1.
   You can use this software according to the terms and conditions of the Mulan PSL v1.
   You may obtain a copy of Mulan PSL v1 at:
      http://license.coscl.org.cn/MulanPSL
   THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
   PURPOSE.
   See the Mulan PSL v1 for more details.*/
#include "jwl_http.h"
#if JWL_HTTP_ENABLE==1
jwl_http_head *jwl_http_head_new()
{
	return jwl_http_head_init(jbl_malloc(sizeof(jwl_http_head)));
}
jwl_http_head *jwl_http_head_init(jwl_http_head * this)
{
	if(!this)jbl_exception("NULL POINTER");		
	jbl_gc_init(this);
	jbl_gc_plus(this);
	jwl_http_head_set_response(this);
	this->status		=0;
	this->charset		=0;	

	this->method		=0;
	this->protocol		=0;
	this->connection	=0;
	
	this->cache			=0;
	this->cache_max_age	=0;	
	this->range.start	=0;	
	this->range.end		=0;	
	this->etag			=NULL;

//jbl_string
	this->content_type	=NULL;
	this->filename		=NULL;

	this->url			=NULL;
	this->host			=NULL;
	this->ua			=NULL;
	this->referer		=NULL;
//jbl_ht
	this->cookie		=NULL;
	this->v				=NULL;	
	return this;
}
jwl_http_head *jwl_http_head_free(jwl_http_head * this)
{
	if(!this)return NULL;
	jbl_gc_minus(this);
	if(!jbl_gc_refcnt(this))
	{
		if(jbl_gc_is_ref(this))
			jwl_http_head_free((jwl_http_head*)(((jbl_reference*)this)->ptr));
		else
		{
			this->etag			=jbl_string_free(this->etag);
			
			this->content_type	=jbl_string_free(this->content_type);
			this->filename		=jbl_string_free(this->filename);
			
			this->url			=jbl_string_free(this->url);
			this->host			=jbl_string_free(this->host);
			this->ua			=jbl_string_free(this->ua);
			this->referer		=jbl_string_free(this->referer);
			
			this->v				=jbl_ht_free	(this->v);
			this->cookie		=jbl_ht_free	(this->v);
		}
		if(jbl_gc_is_var(this))//因为该功能依赖jbl_ht,jbl_ht强制依赖var所以不用宏判断
			jbl_free((char*)this-sizeof(jbl_var));
		else
			jbl_free(this);
	}
	return NULL;	
	
}
inline jwl_http_head *jwl_http_head_copy(jwl_http_head * this)
{
	jbl_gc_plus(this);
	return this;
}
inline jwl_http_head *jwl_http_head_extend(jwl_http_head * this,jwl_http_head **pthi)
{
	if(!this){this=jwl_http_head_new();if(pthi)*pthi=this;return this;}
	jbl_reference *ref=NULL;jwl_http_head *thi=jbl_refer_pull_keep_father(this,&ref);
	if(jbl_gc_is_pvar(thi))
	{
		jwl_http_head *ttt=((jbl_reference*)thi)->ptr;
		if(jbl_gc_refcnt(thi)==1)
			((jbl_reference*)thi)->ptr=NULL,pl();
		jwl_http_head_free(thi);
		thi=ttt;
	}	
	if((jbl_gc_refcnt(thi)<=1)){if(pthi)*pthi=thi;return this;}

	jwl_http_head * tmp	=jwl_http_head_new();
	
	tmp->status			=this->status;
	tmp->charset		=this->charset;
	
	tmp->method			=this->method;
	tmp->protocol		=this->protocol;
	tmp->connection		=this->connection;
	
	tmp->cache			=this->cache;
	tmp->cache_max_age	=this->cache_max_age;
	tmp->range.start	=this->range.start;
	tmp->range.end		=this->range.end;
	tmp->etag			=jbl_string_copy(this->etag);
	
	
	tmp->content_type	=jbl_string_copy(this->content_type);
	tmp->filename		=jbl_string_copy(this->filename);
	
	
	tmp->url			=jbl_string_copy(this->url);
	tmp->host			=jbl_string_copy(this->host);
	tmp->ua				=jbl_string_copy(this->ua);
	tmp->referer		=jbl_string_copy(this->referer);
	
	tmp->cookie			=jbl_ht_copy(this->cookie);
	tmp->v				=jbl_ht_copy(this->v);
	
	jwl_http_head_free(this);
	if(ref)		ref->ptr=tmp;
	else		this=tmp;
	if(pthi)	*pthi=tmp;	
	return this;
}
jwl_http_head * jwl_http_head_set_status			(jwl_http_head * this,jbl_uint16 status)				{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->status		=status			;return this;}
jwl_http_head * jwl_http_head_set_cache				(jwl_http_head * this,jbl_uint16 cache)					{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->cache			=cache  		;return this;}
jwl_http_head * jwl_http_head_set_charset			(jwl_http_head * this,jbl_uint16 charset)				{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->charset		=charset  		;return this;}
jwl_http_head * jwl_http_head_set_cache_max_age		(jwl_http_head * this,jbl_uint32 cache_max_age)			{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->cache_max_age	=cache_max_age	;return this;}
jwl_http_head * jwl_http_head_set_content_type		(jwl_http_head * this,jbl_string * content_type)		{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);jbl_string_free(thi->content_type)	;thi->content_type	=jbl_string_copy(content_type)	;return this;}
jwl_http_head * jwl_http_head_set_etag				(jwl_http_head * this,jbl_string * etag)				{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);jbl_string_free(thi->etag)			;thi->etag			=jbl_string_copy(etag)			;return this;}
jwl_http_head *	jwl_http_head_set_range				(jwl_http_head * this,jbl_uint64 start,jbl_uint64 end)	{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);thi->range.start=start;thi->range.end=end;return this;}
jwl_http_head * jwl_http_head_set_filename			(jwl_http_head * this,jbl_string * filename)			{jwl_http_head *thi;this=jwl_http_head_extend(this,&thi);jbl_string_free(thi->filename)		;thi->filename		=jbl_string_copy(filename)		;return this;}
//jwl_http_head * jwl_http_head_set					(jwl_http_head * this,jbl_string * k, jbl_var *v);



void jwl_http_head_encode(jbl_stream *stream,jwl_http_head *head,jbl_string_size_type size)
{
#define rn() jbl_stream_push_char(stream,'\r'),jbl_stream_push_char(stream,'\n')
	if(!head)return;
	head=jbl_refer_pull(head);
	jbl_stream_push_chars(stream,UC"HTTP/1.1 ");
	jbl_stream_push_uint(stream,head->status);
	switch(head->status)
	{
		case 200:	jbl_stream_push_chars(stream,UC" OK")				;break;
		case 206:	jbl_stream_push_chars(stream,UC" Partial Content")	;break;
		case 304:	jbl_stream_push_chars(stream,UC" Not Modified")		;break;
		case 404:	jbl_stream_push_chars(stream,UC" Not Found")		;break;
		case 416:	jbl_stream_push_chars(stream,UC" Range Not Satisfiable")		;break;
	}
	rn();
	jbl_stream_push_chars(stream,UC"Server: "JWL_HTTP_RESPONSE_SERVER_NAME)															,rn();
	if(head->status==206)
	{
		jbl_stream_push_chars(stream,UC"Content-Length: ")					,jbl_stream_push_uint(stream,(head->range.end?head->range.end:size)-head->range.start)	,rn();
		//注意，range是闭区间，而jwl,jbl要求左闭右开区间
		jbl_stream_push_chars(stream,UC"Content-Range: bytes ")				,jbl_stream_push_uint(stream,head->range.start)			,jbl_stream_push_char(stream,'-')	,jbl_stream_push_uint(stream,head->range.end?(head->range.end-1):0)	,jbl_stream_push_char(stream,'/')	,jbl_stream_push_uint(stream,size)	,rn();
	}
	else
		jbl_stream_push_chars(stream,UC"Content-Length: ")					,jbl_stream_push_uint(stream,size)						,rn();
	jbl_stream_push_chars(stream,UC"Accept-Ranges: bytes")																			,rn();
	if(head->cache==JWL_HTTP_CACHE_MAX_AGE)
	{
		jbl_stream_push_chars(stream,UC"Cache-Control: max-age=")	,jbl_stream_push_uint(stream,head->cache_max_age)				,rn();
		jbl_time * t=jbl_time_add_second(jbl_time_now(NULL),head->cache_max_age);
//		jbl_stream_push_chars(stream,UC"Date: ")	,jbl_time_to_string_format(t,stream,UC JBL_TIME_FORMAT_RFC1123)					,rn();
//		jbl_stream_push_chars(stream,UC"Expires: ")	,jbl_time_to_string_format(t,stream,UC JBL_TIME_FORMAT_RFC1123)					,rn();
		t=jbl_time_free(t);
	}
	else
	{
		jbl_stream_push_chars(stream,UC"Pragma: no-cache")																			,rn();
		jbl_stream_push_chars(stream,UC"Cache-Control: no-cache")																	,rn();
	}
	if(head->content_type)
	{
		jbl_stream_push_chars(stream,UC"Content-Type: ")					,jbl_stream_push_string(stream,head->content_type);
		char *charset[]={"","UTF-8"};
		if(head->charset)
			jbl_stream_push_chars(stream,UC"; charset=")					,jbl_stream_push_chars(stream,UC charset[head->charset]);
		rn();
	}
	if(head->etag)
		jbl_stream_push_chars(stream,UC"ETag: ")							,jbl_stream_push_string(stream,head->etag)				,rn();
	if(head->filename)
	{
		jbl_stream_push_chars(stream,UC"Content-Disposition: attachment; filename=\"");
		jbl_stream_push_string(stream,head->filename);
		jbl_stream_push_char(stream,'"');
		rn();
	}
	if(head->v)
		jbl_ht_foreach(head->v,i)
		{
			jbl_stream_push_string(stream,jbl_htk(i));
			jbl_stream_push_chars(stream,UC": ");
//			jbl_string_add_var(&stream,jbl_htv(i));
			rn();
		}
	
	
	
//	jbl_stream_push_chars(stream,UC"Connection: keep-alive");rn();
//	jbl_stream_push_chars(stream,UC"Keep-Alive: timeout=4");rn();
//	jbl_stream_push_chars(stream,UC"Proxy-Connection: keep-alive");rn();
	
	rn();
#undef rn
}
jwl_http_key __jwl_http_rqhd_scanner(unsigned char * YYCURSOR,unsigned char * YYLIMIT,unsigned char **addr)
{
	unsigned char *		YYMARKER;
	#define YYCTYPE		unsigned char
	#define YYFILL(n)	return JWL_HTTP_KEY_END;
    
#line 227 "jwl/jwl_http.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 17) YYFILL(17);
	yych = *YYCURSOR;
	switch (yych) {
	case '\r':	goto yy4;
	case 'A':	goto yy5;
	case 'C':	goto yy6;
	case 'E':	goto yy7;
	case 'H':	goto yy8;
	case 'I':	goto yy9;
	case 'R':	goto yy10;
	case 'U':	goto yy11;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
yy3:
#line 224 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_UNDEFINED;}
#line 248 "jwl/jwl_http.c"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy12;
	default:	goto yy3;
	}
yy5:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'c':	goto yy14;
	default:	goto yy3;
	}
yy6:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy15;
	case 'o':	goto yy16;
	default:	goto yy3;
	}
yy7:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 't':	goto yy17;
	default:	goto yy3;
	}
yy8:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy18;
	default:	goto yy3;
	}
yy9:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'f':	goto yy19;
	default:	goto yy3;
	}
yy10:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy20;
	case 'e':	goto yy21;
	default:	goto yy3;
	}
yy11:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 's':	goto yy22;
	default:	goto yy3;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\r':	goto yy23;
	default:	goto yy13;
	}
yy13:
	YYCURSOR = YYMARKER;
	goto yy3;
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy24;
	default:	goto yy13;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy25;
	default:	goto yy13;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy26;
	default:	goto yy13;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy27;
	default:	goto yy13;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy28;
	default:	goto yy13;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy29;
	default:	goto yy13;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy30;
	default:	goto yy13;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy31;
	default:	goto yy13;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy32;
	default:	goto yy13;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\n':	goto yy33;
	default:	goto yy13;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy35;
	default:	goto yy13;
	}
yy25:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy36;
	default:	goto yy13;
	}
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy37;
	default:	goto yy13;
	}
yy27:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy38;
	default:	goto yy13;
	}
yy28:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy39;
	default:	goto yy13;
	}
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':	goto yy40;
	default:	goto yy13;
	}
yy30:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy41;
	default:	goto yy13;
	}
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy42;
	default:	goto yy13;
	}
yy32:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy43;
	default:	goto yy13;
	}
yy33:
	++YYCURSOR;
#line 225 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_END;}
#line 426 "jwl/jwl_http.c"
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy44;
	default:	goto yy13;
	}
yy36:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy45;
	default:	goto yy13;
	}
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy46;
	default:	goto yy13;
	}
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy47;
	default:	goto yy13;
	}
yy39:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy48;
	default:	goto yy13;
	}
yy40:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy49;
	default:	goto yy13;
	}
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy50;
	default:	goto yy13;
	}
yy42:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy51;
	default:	goto yy13;
	}
yy43:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy52;
	default:	goto yy13;
	}
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy53;
	default:	goto yy13;
	}
yy45:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy54;
	default:	goto yy13;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy55;
	default:	goto yy13;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy56;
	default:	goto yy13;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy58;
	default:	goto yy13;
	}
yy49:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy60;
	default:	goto yy13;
	}
yy50:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy61;
	default:	goto yy13;
	}
yy51:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy62;
	default:	goto yy13;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':	goto yy63;
	default:	goto yy13;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy64;
	case ':':	goto yy65;
	default:	goto yy13;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy66;
	default:	goto yy13;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy67;
	default:	goto yy13;
	}
yy56:
	++YYCURSOR;
#line 234 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_ETAG;}
#line 558 "jwl/jwl_http.c"
yy58:
	++YYCURSOR;
#line 226 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_HOST;}
#line 563 "jwl/jwl_http.c"
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy68;
	default:	goto yy13;
	}
yy61:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy69;
	default:	goto yy13;
	}
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy70;
	default:	goto yy13;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy71;
	default:	goto yy13;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'E':	goto yy72;
	case 'L':	goto yy73;
	default:	goto yy13;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy74;
	default:	goto yy13;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy76;
	default:	goto yy13;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy77;
	default:	goto yy13;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case '-':	goto yy79;
	default:	goto yy13;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy80;
	default:	goto yy13;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy81;
	default:	goto yy13;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy82;
	default:	goto yy13;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy83;
	default:	goto yy13;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy84;
	default:	goto yy13;
	}
yy74:
	++YYCURSOR;
#line 228 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_ACCEPT;}
#line 653 "jwl/jwl_http.c"
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy85;
	default:	goto yy13;
	}
yy77:
	++YYCURSOR;
#line 232 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_CACHE_CONTROL;}
#line 664 "jwl/jwl_http.c"
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy86;
	default:	goto yy13;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy87;
	default:	goto yy13;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy88;
	default:	goto yy13;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy90;
	default:	goto yy13;
	}
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy91;
	default:	goto yy13;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy92;
	default:	goto yy13;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy93;
	default:	goto yy13;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy94;
	default:	goto yy13;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy95;
	default:	goto yy13;
	}
yy88:
	++YYCURSOR;
#line 233 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_REFERER;}
#line 723 "jwl/jwl_http.c"
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy96;
	default:	goto yy13;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy97;
	default:	goto yy13;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy98;
	default:	goto yy13;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy99;
	default:	goto yy13;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy100;
	default:	goto yy13;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy101;
	default:	goto yy13;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy102;
	default:	goto yy13;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy103;
	default:	goto yy13;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy104;
	default:	goto yy13;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy105;
	default:	goto yy13;
	}
yy100:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy106;
	default:	goto yy13;
	}
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy107;
	default:	goto yy13;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy108;
	default:	goto yy13;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy110;
	default:	goto yy13;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy111;
	default:	goto yy13;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy112;
	default:	goto yy13;
	}
yy106:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy113;
	default:	goto yy13;
	}
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy114;
	default:	goto yy13;
	}
yy108:
	++YYCURSOR;
#line 227 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_UA;}
#line 836 "jwl/jwl_http.c"
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy116;
	default:	goto yy13;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy117;
	default:	goto yy13;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy118;
	default:	goto yy13;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy119;
	default:	goto yy13;
	}
yy114:
	++YYCURSOR;
#line 236 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_RANGE_BYTES;}
#line 865 "jwl/jwl_http.c"
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy120;
	default:	goto yy13;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy121;
	default:	goto yy13;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy122;
	default:	goto yy13;
	}
yy119:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy124;
	default:	goto yy13;
	}
yy120:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy126;
	default:	goto yy13;
	}
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy127;
	default:	goto yy13;
	}
yy122:
	++YYCURSOR;
#line 231 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_CACHE_CONTROL;}
#line 906 "jwl/jwl_http.c"
yy124:
	++YYCURSOR;
#line 235 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_ETAG;}
#line 911 "jwl/jwl_http.c"
yy126:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy128;
	default:	goto yy13;
	}
yy127:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy130;
	default:	goto yy13;
	}
yy128:
	++YYCURSOR;
#line 229 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_ACCEPT_ENCODING;}
#line 928 "jwl/jwl_http.c"
yy130:
	++YYCURSOR;
#line 230 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_KEY_ACCEPT_LANGUAGE;}
#line 933 "jwl/jwl_http.c"
}
#line 237 "jwl/jwl_http.l"

	#undef YYCTYPE
	#undef YYFILL
}
jwl_http_method __jwl_http_method_scanner(unsigned char * YYCURSOR,unsigned char * YYLIMIT,unsigned char **addr)
{
	unsigned char *		YYMARKER;
	#define YYCTYPE		unsigned char
	#define YYFILL(n)	return 0;
    
#line 946 "jwl/jwl_http.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
	case 'G':	goto yy136;
	case 'P':	goto yy137;
	default:	goto yy134;
	}
yy134:
	++YYCURSOR;
yy135:
#line 247 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_METHOD_UNKNOW;}
#line 961 "jwl/jwl_http.c"
yy136:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':	goto yy138;
	default:	goto yy135;
	}
yy137:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'O':	goto yy140;
	default:	goto yy135;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy141;
	default:	goto yy139;
	}
yy139:
	YYCURSOR = YYMARKER;
	goto yy135;
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy143;
	default:	goto yy139;
	}
yy141:
	++YYCURSOR;
#line 249 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_METHOD_GET;}
#line 993 "jwl/jwl_http.c"
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy144;
	default:	goto yy139;
	}
yy144:
	++YYCURSOR;
#line 248 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_METHOD_POST;}
#line 1004 "jwl/jwl_http.c"
}
#line 250 "jwl/jwl_http.l"

	#undef YYCTYPE
	#undef YYFILL
}
jwl_http_protocol __jwl_http_protocol_scanner(unsigned char * YYCURSOR,unsigned char * YYLIMIT,unsigned char **addr)
{
	unsigned char *		YYMARKER;
	#define YYCTYPE		unsigned char
	#define YYFILL(n)	return 0;
    
#line 1017 "jwl/jwl_http.c"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 8) YYFILL(8);
	yych = *YYCURSOR;
	switch (yych) {
	case 'H':	goto yy150;
	default:	goto yy148;
	}
yy148:
	++YYCURSOR;
yy149:
#line 260 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_PROTOCOL_UNKNOW;}
#line 1031 "jwl/jwl_http.c"
yy150:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'T':	goto yy151;
	default:	goto yy149;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy153;
	default:	goto yy152;
	}
yy152:
	YYCURSOR = YYMARKER;
	goto yy149;
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':	goto yy154;
	default:	goto yy152;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case '/':	goto yy155;
	default:	goto yy152;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':	goto yy156;
	default:	goto yy152;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy157;
	default:	goto yy152;
	}
yy157:
	yych = *++YYCURSOR;
	switch (yych) {
	case '1':	goto yy158;
	default:	goto yy152;
	}
yy158:
	++YYCURSOR;
#line 261 "jwl/jwl_http.l"
	{if(addr)*addr=YYCURSOR;return JWL_HTTP_PROTOCOL_HTTP;}
#line 1081 "jwl/jwl_http.c"
}
#line 262 "jwl/jwl_http.l"

	#undef YYCTYPE
	#undef YYFILL
}

jwl_http_head* jwl_http_head_decode(jbl_string *buf,jbl_string_size_type *start)
{	
	if(!buf)return NULL;
	buf=jbl_refer_pull(buf);
	jbl_string_size_type i=0;if(start)i=*start;
	unsigned char *addr;
	jwl_http_head * head=jwl_http_head_new();
	jwl_http_head_set_request(head);
	
	head->method=__jwl_http_method_scanner(buf->s+i,buf->s+buf->len,&addr);i=addr-buf->s;
	
	for(++i;buf->s[i]!=' ';head->url=jbl_string_add_char(head->url,buf->s[i]),++i);++i;
	
	head->protocol=__jwl_http_protocol_scanner(buf->s+i,buf->s+buf->len,&addr);i=addr-buf->s;

	for(;i<buf->len;++i)
	{
		jwl_http_key key=__jwl_http_rqhd_scanner(buf->s+i,buf->s+buf->len,&addr);
		switch(key)
		{
			case JWL_HTTP_KEY_END				:goto finish;																																							;break;
			case JWL_HTTP_KEY_UA				:for(i=addr-buf->s;i<buf->len&&buf->s[i-1]!='\r'&&buf->s[i]!='\n'	;head->ua		=jbl_string_add_char(head->ua		,buf->s[i]),++i)	;--head->ua->len			;break;
			case JWL_HTTP_KEY_HOST				:for(i=addr-buf->s;i<buf->len&&buf->s[i-1]!='\r'&&buf->s[i]!='\n'	;head->host		=jbl_string_add_char(head->host		,buf->s[i]),++i)	;--head->host->len			;break;
			case JWL_HTTP_KEY_REFERER			:for(i=addr-buf->s;i<buf->len&&buf->s[i-1]!='\r'&&buf->s[i]!='\n'	;head->referer	=jbl_string_add_char(head->referer	,buf->s[i]),++i)	;--head->referer->len		;break;
			case JWL_HTTP_KEY_ETAG				:for(i=addr-buf->s;i<buf->len&&buf->s[i-1]!='\r'&&buf->s[i]!='\n'	;head->etag		=jbl_string_add_char(head->etag		,buf->s[i]),++i)	;--head->etag->len			;break;
			case JWL_HTTP_KEY_RANGE_BYTES		:head->range.start=jbl_string_get_uint_start_end(buf,&i,'-')		;head->range.end=jbl_string_get_uint_start_end(buf,&i,'\r');head->range.end?(head->range.end+=1):0	;break;//注意，range是闭区间，而jwl,jbl要求左闭右开区间
			
			case JWL_HTTP_KEY_COOKIE			:break;
			case JWL_HTTP_KEY_ACCEPT			:break;
			case JWL_HTTP_KEY_ACCEPT_ENCODING	:break;
			case JWL_HTTP_KEY_ACCEPT_LANGUAGE	:break;
			case JWL_HTTP_KEY_CACHE_CONTROL		:break;
			
			
			
			default:break;
		}
		
	}
finish:;
	if(start)*start=i;
	
	
	return head;
}



#if JBL_STREAM_ENABLE==1
jwl_http_head* jwl_http_head_view_put(jwl_http_head* this,jbl_stream *out,jbl_uint8 format,jbl_uint32 tabs,jbl_uint32 line,unsigned char * varname,unsigned char * func,unsigned char * file)
{
	jwl_http_head* thi;if(jbl_stream_view_put_format(thi=jbl_refer_pull(this),out,format,tabs,UC"jwl_http_head",line,varname,func,file)){jbl_stream_push_char(out,'\n');return this;}
	jbl_stream_push_char(out,'\n');
	++tabs;
	char * charset		[]={"unknow","UTF-8"};
	char * method		[]={"unknow","get","post"};
	char * protocol		[]={"unknow","HTTP"};
	char * connection	[]={"unknow","keep alive","close","upgrade"};
	char * cache		[]={"unknow","no","max age,"};
	char * type			[]={"response","request"};
	if(1)
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"type         :");jbl_stream_push_chars(out,UC type			[jwl_http_head_is_request(this)?1:0])	;jbl_stream_push_char(out,'\n');
	if(jwl_http_head_is_response(this))
	{
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"status       :");jbl_stream_push_uint(out,thi->status)								;jbl_stream_push_char(out,'\n');
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"charset      :");jbl_stream_push_chars(out,UC charset		[thi->charset])			;jbl_stream_push_char(out,'\n');
	}
	if(jwl_http_head_is_request(this))
	{
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"method       :");jbl_stream_push_chars(out,UC method		[thi->method])			;jbl_stream_push_char(out,'\n');	
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"protocol     :");jbl_stream_push_chars(out,UC protocol		[thi->protocol])		;jbl_stream_push_char(out,'\n');	
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"connection   :");jbl_stream_push_chars(out,UC connection	[thi->connection])		;jbl_stream_push_char(out,'\n');	
	}
	if(1)
	{
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"cache        :");jbl_stream_push_chars(out,UC cache		[thi->cache])			;if(thi->cache==JWL_HTTP_CACHE_MAX_AGE){jbl_stream_push_uint(out,thi->cache_max_age);}	;jbl_stream_push_char(out,'\n');	
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"range        :");jbl_stream_push_uint(out,thi->range.start)						;jbl_stream_push_char(out,'-' );	jbl_stream_push_uint(out,thi->range.end)			;jbl_stream_push_char(out,'\n');	
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"etag         :");jbl_stream_push_string(out,thi->etag)								;jbl_stream_push_char(out,'\n');
	}
	if(jwl_http_head_is_response(this))
	{
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"content type :");jbl_stream_push_string(out,thi->content_type)						;jbl_stream_push_char(out,'\n');
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"filename     :");jbl_stream_push_string(out,thi->filename)							;jbl_stream_push_char(out,'\n');
	}
	if(jwl_http_head_is_request(this))
	{
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"url          :");jbl_stream_push_string(out,thi->url)								;jbl_stream_push_char(out,'\n');	
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"host         :");jbl_stream_push_string(out,thi->host)								;jbl_stream_push_char(out,'\n');	
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"user agent   :");jbl_stream_push_string(out,thi->ua)								;jbl_stream_push_char(out,'\n');	
		for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);	jbl_stream_push_chars(out,UC"referer      :");jbl_stream_push_string(out,thi->referer)							;jbl_stream_push_char(out,'\n');	
	}	
	if(thi->v)
		jbl_ht_foreach(thi->v,i)
		{
			for(jbl_int32 j=0;j<tabs;jbl_stream_push_char(out,'\t'),++j);//格式化的\t
			jbl_stream_push_char(out,'"'),jbl_stream_push_string(out,i->k),jbl_stream_push_char(out,'"');
			jbl_stream_push_char(out,':');
			jbl_var_view_put(i->v,out,0,tabs,0,NULL,NULL,NULL);
		}
	return this;
/*
	if(format){for(jbl_int32 i=0;i<tabs;jbl_stream_push_char(out,'\t'),++i);}
	jbl_stream_push_chars(out,UC"cache        :"),jbl_stream_push_uint(out,this->cache),jbl_stream_push_char(out,'\t');
	if(this->cache==JWL_HTTP_CACHE_MAX_AGE)
		jbl_stream_push_chars(out,UC"(max-age,"),jbl_stream_push_uint(out,this->cache_max_age),jbl_stream_push_chars(out,UC")\n");
	else
		jbl_stream_push_chars(out,UC"(no-cache)\n");
	jbl_stream_push_chars(out,UC"content type :"),jbl_stream_push_string(out,this->content_type),jbl_stream_push_char(out,'\n');
*/	
}
#endif




#endif
