/* Generated by re2c 1.3 on Sat Oct 10 08:51:35 2020 */
#line 1 "jbl/jbl_scanner.l"
/* Copyright (c) [2020] juruoyun developer team
   Juruoyun basic lib is licensed under the Mulan PSL v1.
   You can use this software according to the terms and conditions of the Mulan PSL v1.
   You may obtain a copy of Mulan PSL v1 at:
      http://license.coscl.org.cn/MulanPSL
   THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
   PURPOSE.
   See the Mulan PSL v1 for more details.*/   
#include "jbl_scanner.h"
#if JBL_SCANNER_ENABLE==1
#if JBL_VAR_ENABLE == 0
#define JBL_SCANNER_KEY_VAR JBL_SCANNER_KEY_UNDEFINED
#define JBL_SCANNER_KEY_JSON JBL_SCANNER_KEY_UNDEFINED
#endif
jbl_scanner_key jbl_scanner(unsigned char * YYCURSOR,unsigned char **addr)
{
	unsigned char * YYMARKER;
	#define YYCTYPE		unsigned char
	
#line 24 "jbl/jbl_scanner.c"
{
	YYCTYPE yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '%':	goto yy4;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
yy3:
#line 22 "jbl/jbl_scanner.l"
	{if(addr)*addr=YYCURSOR;return JBL_SCANNER_KEY_UNDEFINED;}
#line 37 "jbl/jbl_scanner.c"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'X':	goto yy5;
	case 'c':	goto yy7;
	case 'd':	goto yy9;
	case 'e':	goto yy11;
	case 'f':	goto yy13;
	case 'j':	goto yy15;
	case 's':	goto yy17;
	case 'v':	goto yy19;
	default:	goto yy3;
	}
yy5:
	++YYCURSOR;
#line 28 "jbl/jbl_scanner.l"
	{if(addr)*addr=YYCURSOR;return JBL_SCANNER_KEY_HEX;}
#line 55 "jbl/jbl_scanner.c"
yy7:
	++YYCURSOR;
#line 27 "jbl/jbl_scanner.l"
	{if(addr)*addr=YYCURSOR;return JBL_SCANNER_KEY_CHAR;}
#line 60 "jbl/jbl_scanner.c"
yy9:
	++YYCURSOR;
#line 24 "jbl/jbl_scanner.l"
	{if(addr)*addr=YYCURSOR;return JBL_SCANNER_KEY_INT;}
#line 65 "jbl/jbl_scanner.c"
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy21;
	default:	goto yy12;
	}
yy12:
	YYCURSOR = YYMARKER;
	goto yy3;
yy13:
	++YYCURSOR;
#line 25 "jbl/jbl_scanner.l"
	{if(addr)*addr=YYCURSOR;return JBL_SCANNER_KEY_DOUBLE;}
#line 79 "jbl/jbl_scanner.c"
yy15:
	++YYCURSOR;
#line 31 "jbl/jbl_scanner.l"
	{if(addr)*addr=YYCURSOR;return JBL_SCANNER_KEY_JSON;}
#line 84 "jbl/jbl_scanner.c"
yy17:
	++YYCURSOR;
#line 26 "jbl/jbl_scanner.l"
	{if(addr)*addr=YYCURSOR;return JBL_SCANNER_KEY_CHARS;}
#line 89 "jbl/jbl_scanner.c"
yy19:
	++YYCURSOR;
#line 30 "jbl/jbl_scanner.l"
	{if(addr)*addr=YYCURSOR;return JBL_SCANNER_KEY_VAR;}
#line 94 "jbl/jbl_scanner.c"
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy22;
	default:	goto yy12;
	}
yy22:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy23;
	default:	goto yy12;
	}
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy24;
	default:	goto yy12;
	}
yy24:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy25;
	default:	goto yy12;
	}
yy25:
	++YYCURSOR;
#line 29 "jbl/jbl_scanner.l"
	{if(addr)*addr=YYCURSOR;return JBL_SCANNER_KEY_ERRSTR;}
#line 123 "jbl/jbl_scanner.c"
}
#line 32 "jbl/jbl_scanner.l"

	#undef YYCTYPE
	#undef YYFILL	
}



#endif